# Generated by Django 2.0.3 on 2018-05-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180509_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='carversion',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_versions', to='tickets.CarBrand'),
            preserve_default=False,
        ),
    ]
